import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Make the server package root importable (config, db) when Alembic is run
# from the server/ directory.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import settings  # noqa: E402
from db.base import Base  # noqa: E402

# import db.models  # noqa: F401,E402 — uncomment once models exist so they
# register on Base.metadata for autogenerate.

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Inject the real connection URL from central settings (kept out of
# alembic.ini / version control). Alembic uses the sync psycopg2 driver, so
# coerce the scheme. Use the Session Pooler (IPv4) URL — the direct host is
# IPv6-only and the transaction pooler (port 6543) is incompatible with Alembic.
_url = settings.DATABASE_URL.get_secret_value()
if _url.startswith("postgresql://"):
    _url = "postgresql+psycopg2://" + _url[len("postgresql://") :]
elif _url.startswith("postgres://"):
    _url = "postgresql+psycopg2://" + _url[len("postgres://") :]
config.set_main_option("sqlalchemy.url", _url)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# MetaData for 'autogenerate' support. Empty until models are added to
# db/models.py (and imported above).
target_metadata = Base.metadata


def include_object(object, name, type_, reflected, compare_to):
    """Ignore any DB table not defined in our models — LangGraph checkpoint
    tables (owned by langgraph-checkpoint-postgres) and Supabase-managed
    tables must never appear in autogenerated migrations."""
    if type_ == "table" and reflected and name not in target_metadata.tables:
        return False
    return True


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            transaction_per_migration=True,  # each migration rolls back atomically on error
            compare_type=True,
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
