import { internalMutation } from "./_generated/server";

const COURSE_NAME = "Introduction to Python (CSEDM 2019 - A/B Groups)";

type SeedProblem = {
  tag: string;
  problem_name: string;
  week: number;
  knowledge_component: string;
  topic: string;
  problem_description: string;
  starter_code: string;
  solution_code: string;
  testCases: { input: string; expectedOutput: string }[];
};

// Original CSEDM 2019 Problems
const csedmProblems: SeedProblem[] = [
  {
    tag: "csedm",
    problem_name: "helloWorld",
    week: 1,
    knowledge_component: "io_basics",
    topic: "I/O Basics",
    problem_description: "Write a function `hello()` that prints the string 'Hello World!' to the console.",
    starter_code: "def hello():\n    pass",
    solution_code: "def hello():\n    print('Hello World!')",
    testCases: [
      { input: "", expectedOutput: "Hello World!" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "intToFloat",
    week: 2,
    knowledge_component: "io_basics",
    topic: "I/O Basics",
    problem_description: "Write a function `intToFloat(x)` that takes an integer `x` and returns it as a floating point number.",
    starter_code: "def intToFloat(x):\n    pass",
    solution_code: "def intToFloat(x):\n    return float(x)",
    testCases: [
      { input: "5", expectedOutput: "5.0" },
      { input: "-10", expectedOutput: "-10.0" },
      { input: "0", expectedOutput: "0.0" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "doubleX",
    week: 2,
    knowledge_component: "io_basics",
    topic: "I/O Basics",
    problem_description: "Write a function `doubleX(x)` that returns the given number multiplied by 2.",
    starter_code: "def doubleX(x):\n    pass",
    solution_code: "def doubleX(x):\n    return x * 2",
    testCases: [
      { input: "5", expectedOutput: "10" },
      { input: "0", expectedOutput: "0" },
      { input: "-3", expectedOutput: "-6" },
      { input: "2.5", expectedOutput: "5.0" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "raiseToPower",
    week: 2,
    knowledge_component: "arithmetic",
    topic: "Arithmetic",
    problem_description: "Write a function `raiseToPower(base, exponent)` that returns the `base` raised to the power of `exponent`.",
    starter_code: "def raiseToPower(base, exponent):\n    pass",
    solution_code: "def raiseToPower(base, exponent):\n    return base ** exponent",
    testCases: [
      { input: "2 3", expectedOutput: "8" },
      { input: "5 0", expectedOutput: "1" },
      { input: "10 -1", expectedOutput: "0.1" },
      { input: "-2 2", expectedOutput: "4" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "convertToDegrees",
    week: 2,
    knowledge_component: "arithmetic",
    topic: "Arithmetic",
    problem_description: "Write a function `convertToDegrees(radians)` that takes an angle in radians and converts it to degrees. (Assume pi = 3.14159, formula: degrees = radians * 180 / pi, return rounded to 2 decimal places).",
    starter_code: "def convertToDegrees(radians):\n    pass",
    solution_code: "def convertToDegrees(radians):\n    return round(radians * 180 / 3.14159, 2)",
    testCases: [
      { input: "3.14159", expectedOutput: "180.0" },
      { input: "1.570795", expectedOutput: "90.0" },
      { input: "0", expectedOutput: "0.0" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "leftoverCandy",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "Write a function `leftoverCandy(candies, children)` that calculates how many candies are left over if they are divided equally among the children.",
    starter_code: "def leftoverCandy(candies, children):\n    pass",
    solution_code: "def leftoverCandy(candies, children):\n    return candies % children",
    testCases: [
      { input: "10 3", expectedOutput: "1" },
      { input: "15 5", expectedOutput: "0" },
      { input: "2 5", expectedOutput: "2" },
      { input: "100 7", expectedOutput: "2" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "howManyEggCartons",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "Write a function `howManyEggCartons(eggs)` that takes the total number of eggs and returns the number of 12-egg cartons needed to store them (a carton can be partially full).",
    starter_code: "def howManyEggCartons(eggs):\n    pass",
    solution_code: "def howManyEggCartons(eggs):\n    return (eggs + 11) // 12",
    testCases: [
      { input: "24", expectedOutput: "2" },
      { input: "25", expectedOutput: "3" },
      { input: "0", expectedOutput: "0" },
      { input: "1", expectedOutput: "1" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "kthDigit",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "Write a function `kthDigit(n, k)` that returns the k-th digit of the integer `n` from the right (0-indexed, so k=0 is the last digit). If `k` is out of bounds, return 0. Assume `n` is non-negative.",
    starter_code: "def kthDigit(n, k):\n    pass",
    solution_code: "def kthDigit(n, k):\n    return (n // (10**k)) % 10",
    testCases: [
      { input: "1234 0", expectedOutput: "4" },
      { input: "1234 1", expectedOutput: "3" },
      { input: "1234 3", expectedOutput: "1" },
      { input: "1234 5", expectedOutput: "0" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "nearestBusStop",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "There are bus stops every 5 blocks (at block 0, 5, 10, etc.). Write a function `nearestBusStop(street)` that takes a street block number and returns the street block of the nearest bus stop. If it's a tie, round up to the nearest one.",
    starter_code: "def nearestBusStop(street):\n    pass",
    solution_code: "def nearestBusStop(street):\n    return ((street + 2) // 5) * 5",
    testCases: [
      { input: "3", expectedOutput: "5" },
      { input: "2", expectedOutput: "0" },
      { input: "7", expectedOutput: "5" },
      { input: "8", expectedOutput: "10" },
      { input: "10", expectedOutput: "10" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "hasTwoDigits",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `hasTwoDigits(n)` that returns True if the given positive integer `n` has exactly two digits, and False otherwise.",
    starter_code: "def hasTwoDigits(n):\n    pass",
    solution_code: "def hasTwoDigits(n):\n    return 10 <= n <= 99",
    testCases: [
      { input: "10", expectedOutput: "True" },
      { input: "99", expectedOutput: "True" },
      { input: "9", expectedOutput: "False" },
      { input: "100", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "overNineThousand",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `overNineThousand(power_level)` that returns True if `power_level` is strictly greater than 9000, and False otherwise.",
    starter_code: "def overNineThousand(power_level):\n    pass",
    solution_code: "def overNineThousand(power_level):\n    return power_level > 9000",
    testCases: [
      { input: "9001", expectedOutput: "True" },
      { input: "9000", expectedOutput: "False" },
      { input: "8999", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "canDrinkAlcohol",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `canDrinkAlcohol(age)` that returns True if `age` is 21 or older, and False otherwise.",
    starter_code: "def canDrinkAlcohol(age):\n    pass",
    solution_code: "def canDrinkAlcohol(age):\n    return age >= 21",
    testCases: [
      { input: "21", expectedOutput: "True" },
      { input: "22", expectedOutput: "True" },
      { input: "20", expectedOutput: "False" },
      { input: "0", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "isEvenPositiveInt",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `isEvenPositiveInt(n)` that returns True if `n` is an even positive integer (i.e. strictly greater than 0 and divisible by 2).",
    starter_code: "def isEvenPositiveInt(n):\n    pass",
    solution_code: "def isEvenPositiveInt(n):\n    return n > 0 and n % 2 == 0",
    testCases: [
      { input: "2", expectedOutput: "True" },
      { input: "10", expectedOutput: "True" },
      { input: "0", expectedOutput: "False" },
      { input: "-2", expectedOutput: "False" },
      { input: "3", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "findRoot",
    week: 8,
    knowledge_component: "functions_params",
    topic: "Functions and Parameters",
    problem_description: "Write a function `findRoot(x)` that returns the square root of `x`. You must import the math module and use its sqrt function.",
    starter_code: "def findRoot(x):\n    pass",
    solution_code: "import math\ndef findRoot(x):\n    return math.sqrt(x)",
    testCases: [
      { input: "4", expectedOutput: "2.0" },
      { input: "9", expectedOutput: "3.0" },
      { input: "0", expectedOutput: "0.0" },
      { input: "25", expectedOutput: "5.0" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "isPunctuation",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `isPunctuation(c)` that takes a single character string and returns True if it is one of the following punctuation marks: '.', ',', '!', '?', and False otherwise.",
    starter_code: "def isPunctuation(c):\n    pass",
    solution_code: "def isPunctuation(c):\n    return c in ['.', ',', '!', '?']",
    testCases: [
      { input: "[\".\"]", expectedOutput: "True" },
      { input: "[\"?\"]", expectedOutput: "True" },
      { input: "[\"a\"]", expectedOutput: "False" },
      { input: "[\" \"]", expectedOutput: "False" },
      { input: "[\"-\"]", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "firstAndLast",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `firstAndLast(s)` that takes a string `s` of at least length 1 and returns a new string containing only the first and last characters of `s`.",
    starter_code: "def firstAndLast(s):\n    pass",
    solution_code: "def firstAndLast(s):\n    if len(s) == 1:\n        return s + s\n    return s[0] + s[-1]",
    testCases: [
      { input: "[\"hello\"]", expectedOutput: "ho" },
      { input: "[\"world\"]", expectedOutput: "wd" },
      { input: "[\"a\"]", expectedOutput: "aa" },
      { input: "[\"ab\"]", expectedOutput: "ab" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "backwardsCombine",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `backwardsCombine(s1, s2)` that takes two strings, concatenates `s2` to `s1`, and returns the resulting string in reverse order.",
    starter_code: "def backwardsCombine(s1, s2):\n    pass",
    solution_code: "def backwardsCombine(s1, s2):\n    return (s1 + s2)[::-1]",
    testCases: [
      { input: "[\"abc\", \"def\"]", expectedOutput: "fedcba" },
      { input: "[\"hello\", \"world\"]", expectedOutput: "dlrowolleh" },
      { input: "[\"\", \"a\"]", expectedOutput: "a" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "singlePigLatin",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `singlePigLatin(word)` that takes a lowercase word containing only letters. If the word starts with a vowel (a,e,i,o,u), return the word with 'yay' appended. Otherwise, move the first letter to the end and append 'ay'.",
    starter_code: "def singlePigLatin(word):\n    pass",
    solution_code: "def singlePigLatin(word):\n    vowels = 'aeiou'\n    if word[0] in vowels:\n        return word + 'yay'\n    else:\n        return word[1:] + word[0] + 'ay'",
    testCases: [
      { input: "[\"apple\"]", expectedOutput: "appleyay" },
      { input: "[\"banana\"]", expectedOutput: "ananabay" },
      { input: "[\"eat\"]", expectedOutput: "eatyay" },
      { input: "[\"hello\"]", expectedOutput: "ellohay" },
    ],
  },
  {
    tag: "csedm",
    problem_name: "oneToN",
    week: 5,
    knowledge_component: "loops",
    topic: "Loops",
    problem_description: "Write a function `oneToN(n)` that takes a positive integer `n` and returns a list containing the numbers from 1 up to `n` (inclusive).",
    starter_code: "def oneToN(n):\n    pass",
    solution_code: "def oneToN(n):\n    return list(range(1, n + 1))",
    testCases: [
      { input: "5", expectedOutput: "[1, 2, 3, 4, 5]" },
      { input: "1", expectedOutput: "[1]" },
      { input: "3", expectedOutput: "[1, 2, 3]" },
    ],
  },

];

// Supplementary Analogous Problems
const csedm2Problems: SeedProblem[] = [
  {
    tag: "csedm2",
    problem_name: "helloClass",
    week: 1,
    knowledge_component: "io_basics",
    topic: "I/O Basics",
    problem_description: "Write a function `helloClass()` that prints the string 'Hello Class!' to the console.",
    starter_code: "def helloClass():\n    pass",
    solution_code: "def helloClass():\n    print('Hello Class!')",
    testCases: [
      { input: "", expectedOutput: "Hello Class!" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "floatToInt",
    week: 2,
    knowledge_component: "io_basics",
    topic: "I/O Basics",
    problem_description: "Write a function `floatToInt(x)` that takes a floating point number `x` and returns it as an integer.",
    starter_code: "def floatToInt(x):\n    pass",
    solution_code: "def floatToInt(x):\n    return int(x)",
    testCases: [
      { input: "5.9", expectedOutput: "5" },
      { input: "-10.1", expectedOutput: "-10" },
      { input: "0.0", expectedOutput: "0" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "tripleX",
    week: 2,
    knowledge_component: "io_basics",
    topic: "I/O Basics",
    problem_description: "Write a function `tripleX(x)` that returns the given number multiplied by 3.",
    starter_code: "def tripleX(x):\n    pass",
    solution_code: "def tripleX(x):\n    return x * 3",
    testCases: [
      { input: "5", expectedOutput: "15" },
      { input: "0", expectedOutput: "0" },
      { input: "-3", expectedOutput: "-9" },
      { input: "2.5", expectedOutput: "7.5" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "sumOfSquares",
    week: 2,
    knowledge_component: "arithmetic",
    topic: "Arithmetic",
    problem_description: "Write a function `sumOfSquares(a, b)` that returns the sum of the squares of `a` and `b`.",
    starter_code: "def sumOfSquares(a, b):\n    pass",
    solution_code: "def sumOfSquares(a, b):\n    return (a ** 2) + (b ** 2)",
    testCases: [
      { input: "2 3", expectedOutput: "13" },
      { input: "0 5", expectedOutput: "25" },
      { input: "-2 2", expectedOutput: "8" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "convertToRadians",
    week: 2,
    knowledge_component: "arithmetic",
    topic: "Arithmetic",
    problem_description: "Write a function `convertToRadians(degrees)` that takes an angle in degrees and converts it to radians. (Assume pi = 3.14159, formula: radians = degrees * pi / 180, return rounded to 4 decimal places).",
    starter_code: "def convertToRadians(degrees):\n    pass",
    solution_code: "def convertToRadians(degrees):\n    return round(degrees * 3.14159 / 180, 4)",
    testCases: [
      { input: "180", expectedOutput: "3.1416" },
      { input: "90", expectedOutput: "1.5708" },
      { input: "0", expectedOutput: "0.0" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "remainingSlices",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "Write a function `remainingSlices(slices, people)` that calculates how many pizza slices are left over if they are divided equally among the people.",
    starter_code: "def remainingSlices(slices, people):\n    pass",
    solution_code: "def remainingSlices(slices, people):\n    return slices % people",
    testCases: [
      { input: "10 3", expectedOutput: "1" },
      { input: "15 5", expectedOutput: "0" },
      { input: "8 5", expectedOutput: "3" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "howManyVans",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "Write a function `howManyVans(people)` that takes the total number of people and returns the number of 8-person vans needed to transport them (a van can be partially full).",
    starter_code: "def howManyVans(people):\n    pass",
    solution_code: "def howManyVans(people):\n    return (people + 7) // 8",
    testCases: [
      { input: "16", expectedOutput: "2" },
      { input: "17", expectedOutput: "3" },
      { input: "0", expectedOutput: "0" },
      { input: "1", expectedOutput: "1" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "removeLastDigit",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "Write a function `removeLastDigit(n)` that returns the integer `n` with its rightmost digit removed. Assume `n` is non-negative.",
    starter_code: "def removeLastDigit(n):\n    pass",
    solution_code: "def removeLastDigit(n):\n    return n // 10",
    testCases: [
      { input: "1234", expectedOutput: "123" },
      { input: "9", expectedOutput: "0" },
      { input: "100", expectedOutput: "10" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "nearestWaterFountain",
    week: 2,
    knowledge_component: "modular_arith",
    topic: "Modular Arithmetic",
    problem_description: "There are water fountains every 10 meters (at meter 0, 10, 20, etc.). Write a function `nearestWaterFountain(position)` that takes a position in meters and returns the position of the nearest water fountain. If it's a tie, round up.",
    starter_code: "def nearestWaterFountain(position):\n    pass",
    solution_code: "def nearestWaterFountain(position):\n    return ((position + 5) // 10) * 10",
    testCases: [
      { input: "3", expectedOutput: "0" },
      { input: "8", expectedOutput: "10" },
      { input: "15", expectedOutput: "20" },
      { input: "20", expectedOutput: "20" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "hasThreeDigits",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `hasThreeDigits(n)` that returns True if the given positive integer `n` has exactly three digits, and False otherwise.",
    starter_code: "def hasThreeDigits(n):\n    pass",
    solution_code: "def hasThreeDigits(n):\n    return 100 <= n <= 999",
    testCases: [
      { input: "100", expectedOutput: "True" },
      { input: "999", expectedOutput: "True" },
      { input: "99", expectedOutput: "False" },
      { input: "1000", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "boilingPoint",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `boilingPoint(temp_celsius)` that returns True if `temp_celsius` is greater than or equal to 100, and False otherwise.",
    starter_code: "def boilingPoint(temp_celsius):\n    pass",
    solution_code: "def boilingPoint(temp_celsius):\n    return temp_celsius >= 100",
    testCases: [
      { input: "100", expectedOutput: "True" },
      { input: "105", expectedOutput: "True" },
      { input: "99", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "canVote",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `canVote(age)` that returns True if `age` is 18 or older, and False otherwise.",
    starter_code: "def canVote(age):\n    pass",
    solution_code: "def canVote(age):\n    return age >= 18",
    testCases: [
      { input: "18", expectedOutput: "True" },
      { input: "19", expectedOutput: "True" },
      { input: "17", expectedOutput: "False" },
      { input: "0", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "isOddNegativeInt",
    week: 4,
    knowledge_component: "conditionals",
    topic: "Conditionals",
    problem_description: "Write a function `isOddNegativeInt(n)` that returns True if `n` is an odd negative integer (i.e. strictly less than 0 and not divisible by 2).",
    starter_code: "def isOddNegativeInt(n):\n    pass",
    solution_code: "def isOddNegativeInt(n):\n    return n < 0 and n % 2 != 0",
    testCases: [
      { input: "-3", expectedOutput: "True" },
      { input: "-1", expectedOutput: "True" },
      { input: "0", expectedOutput: "False" },
      { input: "-2", expectedOutput: "False" },
      { input: "3", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "findLog",
    week: 8,
    knowledge_component: "functions_params",
    topic: "Functions and Parameters",
    problem_description: "Write a function `findLog(x)` that returns the base-10 logarithm of `x`. You must import the math module and use its log10 function.",
    starter_code: "def findLog(x):\n    pass",
    solution_code: "import math\ndef findLog(x):\n    return math.log10(x)",
    testCases: [
      { input: "10", expectedOutput: "1.0" },
      { input: "100", expectedOutput: "2.0" },
      { input: "1", expectedOutput: "0.0" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "isVowel",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `isVowel(c)` that takes a single character string and returns True if it is a lowercase vowel ('a', 'e', 'i', 'o', 'u'), and False otherwise.",
    starter_code: "def isVowel(c):\n    pass",
    solution_code: "def isVowel(c):\n    return c in ['a', 'e', 'i', 'o', 'u']",
    testCases: [
      { input: "[\"a\"]", expectedOutput: "True" },
      { input: "[\"e\"]", expectedOutput: "True" },
      { input: "[\"b\"]", expectedOutput: "False" },
      { input: "[\" \"]", expectedOutput: "False" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "firstThree",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `firstThree(s)` that takes a string `s` of at least length 3 and returns a new string containing only the first three characters of `s`.",
    starter_code: "def firstThree(s):\n    pass",
    solution_code: "def firstThree(s):\n    return s[:3]",
    testCases: [
      { input: "[\"hello\"]", expectedOutput: "hel" },
      { input: "[\"world\"]", expectedOutput: "wor" },
      { input: "[\"abc\"]", expectedOutput: "abc" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "reverseAndCapitalize",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `reverseAndCapitalize(s)` that takes a string, reverses it, and converts it entirely to uppercase.",
    starter_code: "def reverseAndCapitalize(s):\n    pass",
    solution_code: "def reverseAndCapitalize(s):\n    return s[::-1].upper()",
    testCases: [
      { input: "[\"abc\"]", expectedOutput: "CBA" },
      { input: "[\"hello\"]", expectedOutput: "OLLEH" },
      { input: "[\"a\"]", expectedOutput: "A" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "secretCode",
    week: 3,
    knowledge_component: "string_manip",
    topic: "String Manipulation",
    problem_description: "Write a function `secretCode(word)` that takes a string, reverses it, and appends 'xyz' to the end.",
    starter_code: "def secretCode(word):\n    pass",
    solution_code: "def secretCode(word):\n    return word[::-1] + 'xyz'",
    testCases: [
      { input: "[\"apple\"]", expectedOutput: "elppaxyz" },
      { input: "[\"cat\"]", expectedOutput: "tacxyz" },
      { input: "[\"a\"]", expectedOutput: "axyz" },
    ],
  },
  {
    tag: "csedm2",
    problem_name: "nToOne",
    week: 5,
    knowledge_component: "loops",
    topic: "Loops",
    problem_description: "Write a function `nToOne(n)` that takes a positive integer `n` and returns a list containing the numbers counting down from `n` to 1 (inclusive).",
    starter_code: "def nToOne(n):\n    pass",
    solution_code: "def nToOne(n):\n    return list(range(n, 0, -1))",
    testCases: [
      { input: "5", expectedOutput: "[5, 4, 3, 2, 1]" },
      { input: "1", expectedOutput: "[1]" },
      { input: "3", expectedOutput: "[3, 2, 1]" },
    ],
  },

];

export const seedQuestions = internalMutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("course").collect();
    const match = existing.find((c) => c.course_name === COURSE_NAME);
    if (match) {
      return {
        success: true,
        skipped: true,
        courseId: match._id,
        insertedCount: 0,
      };
    }

    const courseId = await ctx.db.insert("course", {
      course_name: COURSE_NAME,
      course_language: "Python",
    });

    let insertedCount = 0;
    for (const problem of [...csedmProblems, ...csedm2Problems]) {
      await ctx.db.insert("questions", {
        week: problem.week,
        course: courseId,
        problem_name: problem.problem_name,
        problem_description: problem.problem_description,
        knowledge_component: problem.knowledge_component,
        topic: problem.topic,
        tag: problem.tag,
        starter_code: problem.starter_code,
        solution_code: problem.solution_code,
        testCases: problem.testCases,
      });
      insertedCount++;
    }

    return {
      success: true,
      skipped: false,
      courseId,
      insertedCount,
    };
  },
});
